### ISSUE TITLE
Links design

### ISSUE THREAD

**Issue by razvan925** [neveldo/jQuery-Mapael#116]
Hello

I have a question regarding the links design. I am using a class for all links in the map and the animation code looks like this:

.Link {
    stroke-dasharray: 1000;  
    stroke-dashoffset: 1000;  
    stroke-width: 1;  
    stroke: #4caf50; 
    animation: dash 5s linear  infinite;
}

@keyframes dash {

    to {
        stroke-dashoffset: 0;
    }
}

This animation creates a line that starts from a plot A and extends itself to a plot B. When the link reaches plot B i want it to start disappearing from plot A to plot B. Is that possible?

Thanks,
Razvan

**Comment by Indigo744** [comment]
Hello,

Do you mean something like this:
```css
.Link {
   stroke-dasharray: 1000;
   stroke-dashoffset: 1000;
   stroke-width: 1;
   stroke: #4caf50;
   animation: 
      dash_in 5s linear,
      dash_out 5s 5s linear;
}

@keyframes dash_in {
  from {
    stroke-dashoffset: 1000;
  }
  to {
    stroke-dashoffset: 0;
  }
}
@keyframes dash_out {
  from {
    stroke-dashoffset: 0;
  }
  to {
    stroke-dashoffset: -1000;
  }
}
```

JSFiddle: http://jsfiddle.net/wa39a5hk/
