### ISSUE TITLE
Text not displaying correctly

### ISSUE THREAD

**Issue by sk8sta13** [neveldo/jQuery-Mapael#72]
Hello,

I`ve downloaded the example available on github, and tried to run it in internet explorer 8 to test. Them map is loaded correctly but the texts are not, they are all in the top-left corner.
Is there any alternative to solve this?

**Comment by neveldo** [comment]
Hello,

Sorry for my very late answer. The compatibility information are not up to date for jQuery Mapael. IE<9 is no longer compatible with Mapael. I will update the compatibility information on the readme file.

However, if you need to get mapael working on IE<9, it should works with jQuery 1.11.3 and Raphael.js  2.1.2 dependencies versions. With these versions, mapel should work fine for most of features.

I hope this will help you !

**Comment by Indigo744** [comment]
@sk8sta13 did you set by any chance your container to `display:none` while loading the map?
I had the same issue with the legend: I wanted to hide the legend and show it if the user click on a link.
I suggest you to use `visibility:hidden;` while loading a map.
Note that it will still take the space (it is just not visible).
If you do need to fully hide the map, use the following CSS class:
```css
.map_hide {
    /* display:none is doing some weird stuff on SVG
     * Solution: hide it, then position it far away
     */
    position:absolute !important;
    visibility: hidden !important;
    top:-1000px !important;
    left:-1000px !important; 
}
```
